#!/bin/sh

RUNIT_DIR="$HOME/.runit/runsvdir"

# Arranca runsvdir en primer plano
runsvdir "$RUNIT_DIR" &
RUNIT_PID=$!

# Cuando la sesión muera, limpia TODO
cleanup() {
    sv -w 5 -v down "$RUNIT_DIR"/* 2>/dev/null
    kill -TERM "$RUNIT_PID"
    wait "$RUNIT_PID"
}

trap cleanup EXIT INT TERM HUP

# Espera a que muera la sesión
wait "$RUNIT_PID"
